name: my_flutter_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  image_picker: ^1.1.2
  audioplayers: ^6.4.0
  cupertino_icons: ^1.0.8
  file_picker: ^9.1.0
  camera: ^0.11.1
  tflite_flutter: ^0.11.0
  flutter_tts: ^4.2.2
  flutter_launchers_icon: "^0.11.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_lcons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/kapak.png"